language: ruby
rvm: 
  - '2.2.1'
before_install:
  - sudo curl -L https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb -o /tmp/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i /tmp/vagrant_1.7.2_x86_64.deb
  - sudo curl -L http://download.virtualbox.org/virtualbox/4.3.28/virtualbox-4.3_4.3.28-100309~Ubuntu~precise_amd64.deb -o /tmp/virtualbox-4.3_4.3.28-100309~Ubuntu~precise_amd64.deb
  - sudo apt-get -y update
  - sudo apt-get install -y libsdl1.2debian
  - sudo apt-get install -y libvpx1
  - sudo dpkg -i /tmp/virtualbox-4.3_4.3.28-100309~Ubuntu~precise_amd64.deb
  - sudo curl -sSL https://get.rvm.io | sudo bash -s stable --ruby
install:
  - rvm gemset create ruby-2.2.1@vbinfo
  - rvm ruby-2.2.1@vbinfo
  - gem install --version 1.7.15 bundler
  - bundler install
script:
  - rake
